### ISSUE TITLE
System explorer displays all parameters under the first label after import

### ISSUE THREAD

**Issue by jkreienh** [NIVeriStandAdd-Ons/Ballard-Arinc-429-Custom-Device#8]
The system explorer will "visually" display all parameters under the first label after import.  The act of refreshing the system explorer after each parameter is dynamically created, creates a very long import process.  At this time, the trade-off of a faster import was more beneficial than the system explorer tree showing the correct parameters under each label and can be remedied with the following steps.

Complete the following steps to "visually" update the system explorer:

1. Save the System Definition after import (All parameters will be listed under the first label)
2. Close the System Definition
3. Re-open the System Definition (All parameters will be listed under the appropriate label)

**Comment by VincentRuault** [comment]
A CAR (Corrective Action Request), in NI-VeriStand Custom Device API, exists for the set of functions used to group the display updates: _CAR 317525_. No target date for that issue to be fixed.

Approach taken: we keep on using that set of functions because it drastically speeds-up Channels Creation process. Where not ideal because of that display bug, as Parameters Channels are defined via a XML File, users will not systematically browse the tree right after loading and there is a workaround.
